# Generated by Django 3.2.7 on 2021-09-30 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ages', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'age_range',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genders', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('workout', models.CharField(max_length=100)),
                ('length', models.IntegerField(null=True)),
                ('repeat', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('age_range_id', models.ManyToManyField(null=True, to='data.AgeRange')),
            ],
            options={
                'db_table': 'workout',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='userimages')),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('age_range_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.agerange', verbose_name='age')),
                ('gender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.gender', verbose_name='gender')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
