# Generated by Django 3.2.7 on 2021-09-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='gender_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.gender', verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age_range_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.agerange', verbose_name='age'),
        ),
    ]
