# Generated by Django 3.2.7 on 2021-09-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='age_range_id',
        ),
        migrations.AddField(
            model_name='workout',
            name='age_range_id',
            field=models.ManyToManyField(null=True, to='data.AgeRange'),
        ),
    ]
