# Generated by Django 3.2.7 on 2021-10-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20211005_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
