# Generated by Django 3.2.7 on 2021-10-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_accounts'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accounts',
            table='accounts',
        ),
    ]
