# Generated by Django 3.2.7 on 2021-10-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_workouts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='length',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
