# Generated by Django 3.2.7 on 2021-10-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20211001_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ageranges',
            name='value',
            field=models.CharField(max_length=100, verbose_name='age range'),
        ),
        migrations.AlterField(
            model_name='genders',
            name='value',
            field=models.CharField(max_length=100, verbose_name='gender'),
        ),
    ]
