# Generated by Django 3.2.7 on 2021-10-01 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_accounts_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='is_compelete',
            new_name='is_compeleted',
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='AccountsProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.accounts')),
                ('age_range_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ageranges')),
            ],
            options={
                'db_table': 'accounts_profiles',
            },
        ),
    ]
