# Generated by Django 3.2.7 on 2021-10-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_workouts_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
