# Generated by Django 3.2.7 on 2021-10-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20211001_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
