# Generated by Django 3.2.7 on 2021-10-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_foods_mealtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtypes',
            name='value',
            field=models.CharField(max_length=100, verbose_name='meal type'),
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.IntegerField(null=True)),
                ('repeat', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('age_range_id', models.ManyToManyField(null=True, to='data.AgeRanges')),
            ],
            options={
                'db_table': 'workout',
            },
        ),
    ]
