# Generated by Django 3.2.7 on 2021-10-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20211002_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='age_range_id',
            field=models.ManyToManyField(to='data.AgeRanges'),
        ),
    ]
