# Generated by Django 3.2.7 on 2021-10-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_workouts_age_range_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouts',
            old_name='age_range_id',
            new_name='age_range',
        ),
        migrations.AddField(
            model_name='workouts',
            name='image',
            field=models.ImageField(null=True, upload_to='workoutsimages'),
        ),
        migrations.CreateModel(
            name='DailyWorkouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('workouts', models.ManyToManyField(to='data.Workouts')),
            ],
            options={
                'db_table': 'daily_workouts',
            },
        ),
    ]
