# Generated by Django 3.2.7 on 2021-09-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
